### ISSUE TITLE
おみくじ結果表示の実装

### ISSUE THREAD

**Issue by uiuxadeadev** [Recursion-teamdev-red/work-space-omikuji#2]
**概要:**  
`drawOmikuji.js`にて、おみくじの結果を表示する機能を実装します。ランダムに選ばれたおみくじの結果（運勢、アドバイス、画像）をユーザーに表示するための動作を実装します。

**目的:**  
おみくじボタンをクリックした後に、ランダムなおみくじの結果を表示し、案内画像とおみくじボタンを非表示にする。また、リセットボタンが表示されるようにします。

---

#### 1. **ランダムなおみくじ結果を選択する関数の実装**
   - [x] `omikujiResults`配列からランダムな結果を選択する処理を追加する。
     - `Math.random()`を使用し、`omikujiResults`の長さに基づいてランダムなインデックスを生成する。
     - `omikujiResults[1]`のように、配列のインデックスにランダムなインデックスを代入し、ランダムな結果を取得する。

#### 2. **結果をHTMLに表示する処理**
   - [x] 選択されたおみくじの運勢、アドバイス、画像をHTMLの該当エリアに挿入する。
   （例） ``` document.getElementById('fortune').innerHTML = `運勢: ${result.fortune}`; ```

#### 3. **結果表示エリアのスタイル変更**
   - [x] `fortune`, `advice`, `omikuji-image`の要素を表示するために、`display`プロパティを`"block"`に設定する。
      （例）```  document.getElementById('fortune').style.display = "block";```
   - [ ] 案内画像とおみくじボタンを非表示にし、リセットボタンを表示する処理を実装する。
      （例） ``` document.getElementById('guide-image').style.display = "none"; ```

#### 4. **DOMの要素操作の動作確認**
   - [x] `fortune`, `advice`, `omikuji-image`の要素に正しくデータが表示されているかを確認する。
   - [x] ボタンの表示/非表示が適切に行われるかを確認する。

---

**受け入れ条件:**
- おみくじボタンを押すと、ランダムにおみくじ結果が表示され、案内画像が非表示になる。
- 結果の運勢、アドバイス、画像が正しく表示されていること。
- リセットボタンが表示され、再度おみくじを引ける状態に戻る。

**Comment by mkanehara** [comment]
@uiuxadeadev 
developブランチに#2をマージした後、再度確認するとリセットボタンが表示されなくなってしまったので、調査中です。

**Comment by mkanehara** [comment]
@uiuxadeadev 
leadクラスのエレメントが削除されていたためでした。修正はリセット機能の実装 #3にて一緒に行います。
![image](https://github.com/user-attachments/assets/4356216a-6d86-45a6-89a9-ed7a58507d32)
